import { AgentPod, CampaignState, ManagerMetric, ActivityEvent } from '@/types';

export const mockCampaignState: CampaignState = {
  id: 'cmp-2026-launch-v2',
  title: 'Q3 Autonomous AI Swarm Launch',
  slogan: 'Next-Gen Orchestrated Content Engine Showcase',
  status: 'in_progress',
  startDate: '2026-09-08',
  endDate: '2026-09-22',
  totalPlannedPosts: 28,
  completedPosts: 16,
  pendingApprovalPosts: 4,
  scheduledPosts: 12,
  platforms: [
    { platform: 'twitter', postCount: 12, enabled: true },
    { platform: 'linkedin', postCount: 8, enabled: true },
    { platform: 'instagram', postCount: 5, enabled: true },
    { platform: 'youtube', postCount: 3, enabled: true },
  ],
  activeSprint: 'Sprint 2: Technical Deep Dives & Benchmark Carousels',
  qualityComplianceRate: 98.4,
  brandSafetyCheckPassed: true,
};

export const mockAgentPods: AgentPod[] = [
  {
    id: 'manager',
    name: 'Manager Agent',
    description: 'Central orchestrator governing pipeline progression, token budgeting, and human approvals',
    status: 'working',
    lead: 'Executive Orchestrator',
    healthScore: 100,
    activeTasksCount: 2,
    completedTasksCount: 34,
    iconName: 'ShieldAlert',
    agents: [
      {
        id: 'mgr-01',
        name: 'Manager Orchestrator Agent',
        role: 'State Machine & Pipeline Gatekeeper',
        pod: 'manager',
        status: 'working',
        currentTask: 'Evaluating Quality Gate output for LinkedIn carousel batch',
        progress: 85,
        model: 'Gemini 1.5 Pro / Ultra Orchestrator',
        tokensUsed: 142500,
        lastActive: 'Just now',
      },
    ],
  },
  {
    id: 'strategy',
    name: 'Strategy Pod',
    description: 'Autonomous market pulse intelligence, trending topic synthesis, and editorial calendar framing',
    status: 'working',
    lead: 'Trend & Research Agent',
    healthScore: 97,
    activeTasksCount: 2,
    completedTasksCount: 18,
    iconName: 'Compass',
    agents: [
      {
        id: 'strat-01',
        name: 'Trend & Research Agent',
        role: 'Semantic Trend & Competitor Signal Extractor',
        pod: 'strategy',
        status: 'working',
        currentTask: 'Synthesizing HackerNews & X algorithmic feed shifts on multi-agent frameworks',
        progress: 92,
        model: 'Gemini 1.5 Flash',
        tokensUsed: 89400,
        lastActive: '1m ago',
      },
      {
        id: 'strat-02',
        name: 'Content Strategy Agent',
        role: 'Editorial Calendar & Brief Architecture',
        pod: 'strategy',
        status: 'idle',
        currentTask: 'Waiting for research digest to build Day 6 hooks',
        progress: 100,
        model: 'Gemini 1.5 Pro',
        tokensUsed: 62100,
        lastActive: '4m ago',
      },
    ],
  },
  {
    id: 'creation',
    name: 'Creation Pod',
    description: 'High-converting copy generation tailored by platform alongside visual asset prompts',
    status: 'working',
    lead: 'Copywriting Agent',
    healthScore: 94,
    activeTasksCount: 3,
    completedTasksCount: 26,
    iconName: 'Sparkles',
    agents: [
      {
        id: 'create-01',
        name: 'Copywriting Agent',
        role: 'Platform-Tuned Long & Short Form Specialist',
        pod: 'creation',
        status: 'working',
        currentTask: 'Drafting 3 viral X thread hooks with high contrast insights',
        progress: 68,
        model: 'Gemini 1.5 Flash',
        tokensUsed: 112000,
        lastActive: 'Just now',
      },
      {
        id: 'create-02',
        name: 'Visual / Design Agent',
        role: 'Infographic Concept & Carousel Layout Prompting',
        pod: 'creation',
        status: 'working',
        currentTask: 'Rendering UI diagram specifications for 5-slide LinkedIn deck',
        progress: 45,
        model: 'Imagen 3 / Gemini Pro Vision',
        tokensUsed: 98400,
        lastActive: '2m ago',
      },
    ],
  },
  {
    id: 'quality',
    name: 'Quality Pod',
    description: 'Automated brand safety filters, factual verification, hallucination checks, and tone fidelity',
    status: 'waiting_approval',
    lead: 'Quality & Brand-Safety Agent',
    healthScore: 99,
    activeTasksCount: 1,
    completedTasksCount: 22,
    iconName: 'ShieldCheck',
    agents: [
      {
        id: 'qual-01',
        name: 'Quality & Brand-Safety Agent',
        role: 'Compliance, Toxicity & Hallucination Auditor',
        pod: 'quality',
        status: 'waiting_approval',
        currentTask: 'Flagged Post #14 (X Thread) - benchmark claim needs human verification',
        progress: 100,
        model: 'Gemini 1.5 Pro (Strict Reasoning)',
        tokensUsed: 78900,
        lastActive: '30s ago',
      },
    ],
  },
  {
    id: 'publishing',
    name: 'Publishing Pod',
    description: 'Native payload packaging, platform rate limit handling, and peak-engagement scheduling',
    status: 'idle',
    lead: 'Scheduling & Publishing Agent',
    healthScore: 100,
    activeTasksCount: 0,
    completedTasksCount: 14,
    iconName: 'SendHorizontal',
    agents: [
      {
        id: 'pub-01',
        name: 'Scheduling & Publishing Agent',
        role: 'Multi-Network API Dispatcher & Time-Zone Optimizer',
        pod: 'publishing',
        status: 'idle',
        currentTask: 'Standing by for human approval on Batch #3',
        progress: 100,
        model: 'Gemini 1.5 Flash',
        tokensUsed: 31200,
        lastActive: '8m ago',
      },
    ],
  },
  {
    id: 'engagement_analytics',
    name: 'Engagement & Analytics Pod',
    description: 'Audience reply monitoring, sentiment clustering, and closing the feedback loop into Strategy Pod',
    status: 'working',
    lead: 'Analytics & Reporting Agent',
    healthScore: 96,
    activeTasksCount: 2,
    completedTasksCount: 42,
    iconName: 'BarChart3',
    agents: [
      {
        id: 'eng-01',
        name: 'Community Engagement Agent',
        role: 'Real-time Comment Triage & Safe Reply Drafting',
        pod: 'engagement_analytics',
        status: 'working',
        currentTask: 'Drafting 6 contextual responses to technical questions on X launch post',
        progress: 80,
        model: 'Gemini 1.5 Flash',
        tokensUsed: 54300,
        lastActive: 'Just now',
      },
      {
        id: 'eng-02',
        name: 'Analytics & Reporting Agent',
        role: 'Click-through & Velocity Attribution Loop',
        pod: 'engagement_analytics',
        status: 'idle',
        currentTask: 'Compiling 24h impression velocity for weekly debrief',
        progress: 100,
        model: 'Gemini 1.5 Pro',
        tokensUsed: 46200,
        lastActive: '12m ago',
      },
    ],
  },
];

export const mockManagerMetrics: ManagerMetric[] = [
  {
    label: 'Campaign Velocity',
    value: '57.1%',
    change: '+14% vs target',
    isPositive: true,
    subtext: '16 of 28 assets produced',
  },
  {
    label: 'Human Approval Queue',
    value: '4 Posts',
    change: 'Requires action',
    isPositive: false,
    subtext: '1 flagged by Quality Pod',
  },
  {
    label: 'Brand Safety Score',
    value: '98.4%',
    change: '+0.6% vs avg',
    isPositive: true,
    subtext: 'Zero policy violations',
  },
  {
    label: 'Active Specialist Agents',
    value: '8 / 9',
    change: '1 Idle',
    isPositive: true,
    subtext: 'All 6 pods operational',
  },
];

export const mockRecentActivity: ActivityEvent[] = [
  {
    id: 'act-01',
    timestamp: '2 mins ago',
    agentName: 'Quality & Brand-Safety Agent',
    pod: 'quality',
    action: 'Flagged Post #14 (X Thread) for Human Review',
    status: 'warning',
    details: 'Unverified benchmark statistic detected in slide 3. Routing to Approval Gate queue.',
  },
  {
    id: 'act-02',
    timestamp: '7 mins ago',
    agentName: 'Manager Orchestrator Agent',
    pod: 'manager',
    action: 'Sequential Handoff: Creation Pod -> Quality Pod',
    status: 'info',
    details: 'Batch #3 (LinkedIn Carousel & X summary) successfully dispatched to Quality Pod.',
  },
  {
    id: 'act-03',
    timestamp: '14 mins ago',
    agentName: 'Visual / Design Agent',
    pod: 'creation',
    action: 'Generated 5 SVG layout drafts',
    status: 'success',
    details: 'Visual assets formatted for 1080x1350 vertical carousel standards.',
  },
  {
    id: 'act-04',
    timestamp: '25 mins ago',
    agentName: 'Copywriting Agent',
    pod: 'creation',
    action: 'Finalized 3 hook variations for LinkedIn Post',
    status: 'success',
    details: 'Flesch-Kincaid grade level: 8.2. High readability score achieved.',
  },
  {
    id: 'act-05',
    timestamp: '42 mins ago',
    agentName: 'Content Strategy Agent',
    pod: 'strategy',
    action: 'Approved Editorial Brief #12',
    status: 'info',
    details: 'Target theme: "Hierarchical Multi-Agent Supervision vs Group Chat Chaos".',
  },
];
