import React from 'react';
import { Calendar as CalendarIcon, Clock, Sparkles } from 'lucide-react';
import { Card, CardHeader, CardTitle } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { mockCampaignState } from '@/lib/mockData';

export default function CalendarPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between p-4 rounded-xl bg-slate-900 border border-slate-800">
        <div>
          <h1 className="text-xl font-bold text-white flex items-center gap-2">
            <CalendarIcon className="h-5 w-5 text-indigo-400" />
            Content Strategy Calendar & Scheduling View
          </h1>
          <p className="text-xs text-slate-400">
            Autonomous multi-network editorial calendar generated by Strategy Pod
          </p>
        </div>
        <Badge variant="purple">{mockCampaignState.scheduledPosts} Posts Queued</Badge>
      </div>

      <Card className="p-8 text-center border-dashed border-slate-800">
        <Clock className="h-10 w-10 text-indigo-400 mx-auto mb-3 animate-pulse" />
        <h3 className="text-base font-semibold text-white mb-1">Calendar & Scheduling Module</h3>
        <p className="text-xs text-slate-400 max-w-md mx-auto mb-4">
          This view will connect the Content Strategy Agent calendar generation with Publishing Pod dispatch times in Milestone 2.
        </p>
      </Card>
    </div>
  );
}
